FROM node:20-alpine AS build
WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_PREFER_SAME_ORIGIN_API
ARG VITE_OAUTH_BASE_URL
ARG VITE_OAUTH_START_PATH
ARG VITE_OAUTH_DIRECT_START_PATH
ARG VITE_USE_DIRECT_OAUTH_START
ARG VITE_PREFER_SAME_ORIGIN_OAUTH_START

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL} \
    VITE_PREFER_SAME_ORIGIN_API=${VITE_PREFER_SAME_ORIGIN_API} \
    VITE_OAUTH_BASE_URL=${VITE_OAUTH_BASE_URL} \
    VITE_OAUTH_START_PATH=${VITE_OAUTH_START_PATH} \
    VITE_OAUTH_DIRECT_START_PATH=${VITE_OAUTH_DIRECT_START_PATH} \
    VITE_USE_DIRECT_OAUTH_START=${VITE_USE_DIRECT_OAUTH_START} \
    VITE_PREFER_SAME_ORIGIN_OAUTH_START=${VITE_PREFER_SAME_ORIGIN_OAUTH_START}

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
